// src/app/question.ts

import { Quiz } from "./quiz"; // Ensure path is correct

export class Question {
    quesId?: number; // Optional, as it's generated by backend
    content: string = '';
    // Removed 'image' property entirely from the model
    option1: string = '';
    option2: string = '';
    option3: string = '';
    option4: string = '';
    answer: string = '';
    givenAnswer?: string; // Used only on frontend for user's input

    // Important: `quiz` must be here to send the association to backend
    // It will typically contain only `qid` when sent from frontend for creation
    quiz?: Quiz;

    // Constructor to initialize properties if needed
    constructor() {
        this.quiz = new Quiz(); // Ensure quiz object is always initialized
    }
}
